---
- name: Create MemoryTools directory 
  ansible.windows.win_file:
    path: C:\MemoryTools
    state: directory

- name: Create Shortcut to Memory Scanners
  ansible.windows.win_shell: |
    $ShortcutPath = "C:\Users\Vagrant\Desktop\MemoryScanners.lnk" 
    $TargetPath = "C:\MemoryTools" 
    $WshShell = New-Object -ComObject WScript.Shell 
    $Shortcut = $WshShell.CreateShortcut($ShortcutPath) 
    $Shortcut.TargetPath = $TargetPath 
    $Shortcut.Save()

- name: Downloading Moneta
  ansible.windows.win_get_url:
    url: '{{ item.url }}'
    dest: 'C:\ProgramData\chocolatey\bin\{{ item.dest }}' 
  with_items:
    - url: https://github.com/forrest-orr/moneta/releases/latest/download/Moneta64.exe
      dest: moneta64.exe

- name: Installing Yara, PE-Sieve
  win_chocolatey:
    name: 
    - yara
    - pesieve

- name: Create Wrapper Scripts
  community.windows.win_lineinfile:
    create: true
    path: 'C:\MemoryTools\{{ item.link }}.cmd'
    line: 'start /b cmd /c "{{ item.target }}" %*'
  with_items:
    - link: Moneta
      target: C:\ProgramData\chocolatey\bin\moneta64.exe
    - link: Yara
      target: C:\ProgramData\chocolatey\bin\yara64.exe
    - link: PE-Sieve
      target: C:\ProgramData\chocolatey\bin\pe-sieve.exe