---
- name: Installing KDE
  ansible.builtin.apt:
    name: task-kde-desktop
    state: latest
  become: yes

- name: Run dhclient on reboot to fix network issues
  ansible.builtin.cron:
    name: Get an IP on reboot
    special_time: reboot
    job: "dhclient"
    user: root  
  become: yes

- name: Removing suspend
  ansible.builtin.shell:
    cmd: |
      for power in LowBattery AC Battery;
      do
        for key in idleTime suspendThenHibernate suspendType;
        do
          kwriteconfig5 --file /home/{{ lookup('env','USER') }}/.config/powermanagementprofilesrc --group $power --group SuspendSession --key $key --delete
        done
      done
    executable: /bin/bash
  become_user: "{{ lookup('env','USER') }}"
  
- name: Disable Screenlocker
  ansible.builtin.shell:
    cmd: |
      kwriteconfig5 --file /home/{{ lookup('env','USER') }}/.config/kscreenlockerrc --group Daemon --key Autolock --type bool false
      kwriteconfig5 --file /home/{{ lookup('env','USER') }}/.config/kscreenlockerrc --group Daemon --key LockOnResume --type bool false
      kwriteconfig5 --file /home/{{ lookup('env','USER') }}/.config/kscreenlockerrc --group Daemon --key Timeout --type string 1
  become_user: "{{ lookup('env','USER') }}"