---
# tasks file for win-common
- name: Ensure chocolatey is installed
  win_chocolatey:
    name:
    - chocolatey
    - chocolatey-core.extension
    state: present

- name: Create directory structure
  ansible.windows.win_file:
    path: C:\Tools
    state: directory

- name: Add exception for C:\Tools
  ansible.windows.win_shell: Add-MpPreference -ExclusionPath C:\Tools

# From: https://github.com/chvancooten/CloudLabsAD/blob/main/Ansible/roles/common/tasks/main.yml
- name: Ensure 'Search' unpinned from the taskbar
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Search
    name: SearchboxTaskbarMode
    data: 0
    type: dword

- name: Ensure 'News and Interests' unpinned from the taskbar
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Feeds
    name: EnableFeeds
    data: 0
    type: dword
    state: present

- name: Ensure 'People' unpinned from the taskbar
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\People
    name: PeopleBand
    data: 0
    type: dword

- name: Ensure 'Edge', 'Store' other built-in shortcuts unpinned from the taskbar
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband
    name: Favorites
    state: absent

- name: Hide Task View, Chat and Cortana, always show file extensions
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: "{{ item }}"
    data: 0
    type: dword
  loop:
    - ShowCortanaButton
    - ShowTaskViewButton
    - TaskbarDa
    - TaskbarMn
    - HideFileExt