---
# tasks file for lin-common
- name: Update system
  block:
    - name: Apt Update
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 0 
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
    - name: Remove dependencies that are no longer required and purge their configuration files
      ansible.builtin.apt:
        autoremove: yes
        purge: true
    - name: Apt Clean
      ansible.builtin.apt:
        clean: yes
  become: yes