workstations:
  hosts:
    dev:
      ansible_host: 10.20.100.100
    victim:
      ansible_host: 10.20.100.101
  vars: 
    ansible_user: "vagrant"
    ansible_password: "vagrant"
    ansible_connection: winrm
    ansible_winrm_scheme: http
    ansible_port: 5985
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_operation_timeout_sec: 60
    ansible_winrm_read_timeout_sec: 120
linux:  
  hosts:
    team-server:
      ansible_host: 10.20.100.200
      ansible_ssh_private_key_file: .vagrant/machines/team-server/virtualbox/private_key
  vars:
    ansible_user: "vagrant"
    ansible_connection: ssh
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
