---
# tasks file for lin-common
- name: Update system
  hosts: localhost
  roles:
    - Roles/lin-common
    - Roles/lin-kde
    - Roles/lin-docker
  vars:
    tools_path: /home/{{ lookup('env','USER') }}/Tools
  become: yes
  tasks:
    - name: Setup Metasploit via docker
      block:
        - name: Pull MSF
          ansible.builtin.shell:
            cmd: docker pull metasploitframework/metasploit-framework
          become: yes
        - name: Copy bash aliases
          ansible.builtin.copy:
            src: Files/bash_aliases_msf
            dest: /home/vagrant/.bash_aliases_msf
            owner: vagrant
            group: vagrant
            mode: '0600'
        - name: Create Bash RC
          ansible.builtin.copy:
            src: /etc/skel/.bashrc
            dest: /home/vagrant/.bashrc
            owner: vagrant
            group: vagrant
            mode: '0644'
            force: false
            remote_src: true

        - name: 
          ansible.builtin.lineinfile:
            path: /home/vagrant/.bashrc
            line: source ~/.bash_aliases_msf
            state: present