---
- name: Dev Machine Provisioning
  hosts: dev
  roles:
    - Roles/win-common
    - Roles/win-choco-debug
    - Roles/win-memscanners
  tasks:
  # Based on instructions from https://www.msys2.org/docs/ci/
    - name: Installing and Configuring GCC
      block:
        - name: Install MSYS
          win_chocolatey:
            name: msys2
            package_params: /InstallDir:C:\msys64
            state: latest

        - name: MSYS2 First Run
          ansible.windows.win_shell: C:\msys64\usr\bin\bash -lc ' '

        - name: MSYS2 Core Update
          ansible.windows.win_shell: C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'

        - name: MSYS2 Normal Update 
          ansible.windows.win_shell: C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'  

        - name: Install GCC via Pacman
          ansible.windows.win_shell: C:\msys64\usr\bin\bash -lc 'pacman -S --needed base-devel mingw-w64-ucrt-x86_64-toolchain mingw-w64-ucrt-x86_64-nasm --noconfirm'

        - name: Add GCC to Path
          ansible.windows.win_path:
            elements: C:\msys64\ucrt64\bin
            state: present
            scope: machine
    
    - name: Installing and configuring Git
      block:
        - name: Install Git via Pacman
          ansible.windows.win_shell: C:\msys64\usr\bin\bash -lc 'pacman -S --needed git --noconfirm'
        - name: Get PHNT Headers
          ansible.windows.win_shell: C:\msys64\usr\bin\bash -lc 'git clone https://github.com/winsiderss/phnt.git C:/phnt'
          args:
            creates: C:\phnt
        - name: Get Elastic Protections
          ansible.windows.win_shell: C:\msys64\usr\bin\bash -lc 'git clone https://github.com/elastic/protections-artifacts.git C:/protections-artifacts'
          args:
            creates: C:\protections-artifacts
    
    - name: Installing Python
      win_chocolatey:
        name: 
        - python
        - git

    - name: Install VSCode with Plugins
      block:
        - name: Installing VSCode
          win_chocolatey:
            name:
            - vscode
        - name: install VSCode plugins
          win_shell: code --install-extension {{ item }}
          with_items:
            - gruntfuggly.todo-tree
            - ms-vscode-remote.vscode-remote-extensionpack
            - ms-python.python
            - ms-vscode.cpptools-extension-pack



  